### ISSUE TITLE
Increase & highlight the scrollable area of Enable platforms in filters page on landscape mode

### ISSUE THREAD

**Issue by Rohijulislam** [Zeronfinity/CPfy#76]
### Description

In Landscape mode,  It's not easily understandable that Enable platforms area of filters page is scrollable. Little increase of height will make UI more user friendly . A screenshot  is attached for better understanding 

![Screenshot_20210125-205020_CPfy](https://user-images.githubusercontent.com/20037046/105723138-9fec0680-5f50-11eb-95fd-0653a8953632.jpg)
]

**Comment by Zeronfinity** [comment]
This might actually be a bug. What model are you using?

![Screenshot_2021-01-25-21-21-20-084_com.zeronfinity.cpfy.jpg](https://user-images.githubusercontent.com/34229687/105725891-aaf46600-5f53-11eb-9fe3-854b1905b034.jpg)

![Screenshot_2021-01-25-21-21-28-294_com.zeronfinity.cpfy.jpg](https://user-images.githubusercontent.com/34229687/105725898-acbe2980-5f53-11eb-9fa0-ba208dbc86fd.jpg)

![Screenshot_2021-01-25-21-22-45-995_com.zeronfinity.cpfy.jpg](https://user-images.githubusercontent.com/34229687/105725901-ae87ed00-5f53-11eb-9247-5f51cfeb680a.jpg)

**Comment by Rohijulislam** [comment]
In my device , area of enable fields is not much. Items are shown in single line & scrollable. Attaching another image & that might be helpful 

![Screenshot_20210125-212608_CPfy 1](https://user-images.githubusercontent.com/20037046/105727005-d3c92b00-5f54-11eb-976f-af4bd7981b7a.jpg)

   

**Device Info:**
- Model : Samsung -J720F 
- Android version : 10

**Comment by Zeronfinity** [comment]
I tried to reproduce the bug in a Galaxy Nexus emulator of the same 720 x 1280 resolution but failed to reproduce the issue. It might be because of the differing screen size and pixel density though.

But I actually found another issue that might be causing what you are observing.

Does the issue always happen for you, I mean is it always a single line or sometimes more lines are shown?

When it's a single line but there are more than 3 platforms, what happens if you click the expand more/less button multiple times? Does it fix the issue?

**Comment by Rohijulislam** [comment]
It could be screen size and pixel density issue.

And yes, Enable platforms always single line in landscape mode with or without expand more/less. But Disable platforms behaving correctly. On expand less, disabled platforms at max double line & on expand more, disabled platforms gets stretched to multi line  to show all the contents

**Comment by Zeronfinity** [comment]
I see. In that case, I will just add some minimum height to expanded for now until I can get a device myself where I can check the issue in detail. 

Thanks a lot for reporting the issue.

**Comment by Rohijulislam** [comment]
Welcome . keep up the great work 👍 .  And kindly let me know if anything else is needed from my side regarding this

**Comment by Zeronfinity** [comment]
Someone else also found this same bug and weirdly, my fix for a similar issue also fixed it in his case, though I am not completely certain how that might have caused exactly this issue.

https://github.com/Zeronfinity/CPfy/actions/runs/510161933

You can also check it by downloading and installing the debug apk from the above link, but it might not be convenient as you need to uninstall the play store release version first just for this testing (another option might be second space if your phone supports that).

Otherwise, we can wait till next update in play store to see if this fix works in your device as well.

**Comment by Rohijulislam** [comment]
FYI
I have tested the debug Apk. Debug apk is working fine in my device.

**Comment by Zeronfinity** [comment]
Oh, that's great. Thank you very much for the feedback.
