### ISSUE TITLE
Some words get cut off in top text view of notification page 

### ISSUE THREAD

**Issue by Rohijulislam** [Zeronfinity/CPfy#81]
## Bug Report

Bug: words get cut off

App version: 1.1.0

Device model:  Samsung J720F with Android version 10.0

### Description

Some words of top text view of notification page are not clearly visible. Seems like some portion of texts sometimes is stretched to outside of text view boundary. A screenshot is added with underling some words for better understanding 

![20210125_235322 1](https://user-images.githubusercontent.com/20037046/105747880-8d32fb00-5f6b-11eb-9d84-7d9c8a9c7f76.jpg)

### Steps to Reproduce

1. Launch the application
2. Click more option of top bar
3. Click notification to navigate  notification page 
4. Observed behaviour

### Expected Result
All word should be visible fully to user

**Comment by zpparmita** [comment]
I want to work on this.

**Comment by Zeronfinity** [comment]
> I want to work on this.

Sure, go ahead. I have assigned the issue to you. Once you have fixed this, just raise a PR and I'll review.

Some general directions:

It seems the issue is due to android:justificationMode in the textview, which is rather new and not well supported. It's not even working properly in most cases, and also not supported before API 26. So I think it can be just removed altogether.

Also, the paddingStart and paddingEnd in this textview should be moved to its parent so that it's applicable to other child textviews as well.
